@istest
public  class CnrServicesWSDLInitTest {
    public static testMethod void runTest()
    {
        CnrServicesWSDL.Get_Fair_element test = new CnrServicesWSDL.Get_Fair_element();
        CnrServicesWSDL.Get_SliderListByLangId_element test1 = new CnrServicesWSDL.Get_SliderListByLangId_element();
        CnrServicesWSDL.Get_NewsResponse_element test2 = new CnrServicesWSDL.Get_NewsResponse_element();
        CnrServicesWSDL.MainSlider test3 = new CnrServicesWSDL.MainSlider();
        CnrServicesWSDL.NewsSlider test4 = new CnrServicesWSDL.NewsSlider();
        CnrServicesWSDL.fuar_user test5 = new CnrServicesWSDL.fuar_user();
        CnrServicesWSDL.GetMailSettingsUtilByMailTopic_element test6 = new CnrServicesWSDL.GetMailSettingsUtilByMailTopic_element();
        CnrServicesWSDL.GetCalendar_element test7 = new CnrServicesWSDL.GetCalendar_element();
        CnrServicesWSDL.Insertbilet_proResponse_element test8 = new CnrServicesWSDL.Insertbilet_proResponse_element();
        CnrServicesWSDL.Get_FairListByLangId_element test9 = new CnrServicesWSDL.Get_FairListByLangId_element();
        CnrServicesWSDL.Get_fuar_userByIDResponse_element test10 = new CnrServicesWSDL.Get_fuar_userByIDResponse_element();
        CnrServicesWSDL.Get_NewsListResponse_element test11 = new CnrServicesWSDL.Get_NewsListResponse_element();
        CnrServicesWSDL.Get_NewsListByWebIdLangId_element test12 = new CnrServicesWSDL.Get_NewsListByWebIdLangId_element();
        CnrServicesWSDL.Getbilet_proByKOD_element test13 = new CnrServicesWSDL.Getbilet_proByKOD_element();
        CnrServicesWSDL.Get_SliderListByWebIdLangId_element test14 = new CnrServicesWSDL.Get_SliderListByWebIdLangId_element();
        CnrServicesWSDL.Get_Slider_element test15 = new CnrServicesWSDL.Get_Slider_element();
        CnrServicesWSDL.GetCalendarResponse_element test16 = new CnrServicesWSDL.GetCalendarResponse_element();
        CnrServicesWSDL.Get_NewsListByWebIdLangIdResponse_element test17 = new CnrServicesWSDL.Get_NewsListByWebIdLangIdResponse_element();
        CnrServicesWSDL.Get_SliderListByWebIdLangIdResponse_element test18 = new CnrServicesWSDL.Get_SliderListByWebIdLangIdResponse_element();
        CnrServicesWSDL.PromotionCodeForInvitationMail_element test19 = new CnrServicesWSDL.PromotionCodeForInvitationMail_element();
        CnrServicesWSDL.Get_FairListByLangIdResponse_element test20 = new CnrServicesWSDL.Get_FairListByLangIdResponse_element();
        CnrServicesWSDL.Get_NewsListByLangId_element test21 = new CnrServicesWSDL.Get_NewsListByLangId_element();
        CnrServicesWSDL.Get_fuar_userByID_element test22 = new CnrServicesWSDL.Get_fuar_userByID_element();
        CnrServicesWSDL.Get_NewsListByLangIdResponse_element test23 = new CnrServicesWSDL.Get_NewsListByLangIdResponse_element();
        CnrServicesWSDL.fuarlar test24 = new CnrServicesWSDL.fuarlar();
        CnrServicesWSDL.Get_SliderResponse_element test25 = new CnrServicesWSDL.Get_SliderResponse_element();
        CnrServicesWSDL.Get_FairList_element test26 = new CnrServicesWSDL.Get_FairList_element();
        CnrServicesWSDL.GenerateCode_element test27 = new CnrServicesWSDL.GenerateCode_element();
        CnrServicesWSDL.Get_FairListByWebIdLangIdResponse_element test28 = new CnrServicesWSDL.Get_FairListByWebIdLangIdResponse_element();
        CnrServicesWSDL.Getbilet_proByKODResponse_element test29 = new CnrServicesWSDL.Getbilet_proByKODResponse_element();
        CnrServicesWSDL.GetMailPatternByMailType_element test30 = new CnrServicesWSDL.GetMailPatternByMailType_element();
        CnrServicesWSDL.GenerateCodeResponse_element test31 = new CnrServicesWSDL.GenerateCodeResponse_element();
        CnrServicesWSDL.Get_News_element test32 = new CnrServicesWSDL.Get_News_element();
        CnrServicesWSDL.ArrayOfMainSlider test33 = new CnrServicesWSDL.ArrayOfMainSlider();
        CnrServicesWSDL.Get_SliderListByLangIdResponse_element test34 = new CnrServicesWSDL.Get_SliderListByLangIdResponse_element();
        CnrServicesWSDL.ArrayOfNewsSlider test35 = new CnrServicesWSDL.ArrayOfNewsSlider();
        CnrServicesWSDL.Get_FairListByWebIdLangId_element test36 = new CnrServicesWSDL.Get_FairListByWebIdLangId_element();
        CnrServicesWSDL.Insertbilet_pro_element test37 = new CnrServicesWSDL.Insertbilet_pro_element();
        CnrServicesWSDL.MailSettingsUtil test38 = new CnrServicesWSDL.MailSettingsUtil();
        CnrServicesWSDL.Get_SliderListResponse_element test39 = new CnrServicesWSDL.Get_SliderListResponse_element();
        CnrServicesWSDL.Getbilet_proByID_element test40 = new CnrServicesWSDL.Getbilet_proByID_element();
        CnrServicesWSDL.GetMailPatternByMailTypeResponse_element test41 = new CnrServicesWSDL.GetMailPatternByMailTypeResponse_element();
        CnrServicesWSDL.Get_NewsList_element test42 = new CnrServicesWSDL.Get_NewsList_element();
        CnrServicesWSDL.Get_NewsListByWebId_element test43 = new CnrServicesWSDL.Get_NewsListByWebId_element();
        CnrServicesWSDL.Get_SliderListByWebIdResponse_element test44 = new CnrServicesWSDL.Get_SliderListByWebIdResponse_element();
        CnrServicesWSDL.Get_NewsListByWebIdResponse_element test45 = new CnrServicesWSDL.Get_NewsListByWebIdResponse_element();
        CnrServicesWSDL.Getbilet_proByIDResponse_element test46 = new CnrServicesWSDL.Getbilet_proByIDResponse_element();
        CnrServicesWSDL.Get_FairResponse_element test47 = new CnrServicesWSDL.Get_FairResponse_element();
        CnrServicesWSDL.ArrayOfFuarlar test48 = new CnrServicesWSDL.ArrayOfFuarlar();
        CnrServicesWSDL.Get_SliderList_element test49 = new CnrServicesWSDL.Get_SliderList_element();
        CnrServicesWSDL.Get_FairListByWebId_element test50 = new CnrServicesWSDL.Get_FairListByWebId_element();
        CnrServicesWSDL.bilet_pro test51 = new CnrServicesWSDL.bilet_pro();
        CnrServicesWSDL.Get_FairListByWebIdResponse_element test52 = new CnrServicesWSDL.Get_FairListByWebIdResponse_element();
        CnrServicesWSDL.MailPatternUtil test53 = new CnrServicesWSDL.MailPatternUtil();
        CnrServicesWSDL.Get_FairListResponse_element test54 = new CnrServicesWSDL.Get_FairListResponse_element();
        CnrServicesWSDL.PromotionCodeForInvitationMailResponse_element test55 = new CnrServicesWSDL.PromotionCodeForInvitationMailResponse_element();
        CnrServicesWSDL.Get_SliderListByWebId_element test56 = new CnrServicesWSDL.Get_SliderListByWebId_element();
        CnrServicesWSDL.GetMailSettingsUtilByMailTopicResponse_element test57 = new CnrServicesWSDL.GetMailSettingsUtilByMailTopicResponse_element();
        CnrServicesWSDL.CnrServiceSoap test58 = new CnrServicesWSDL.CnrServiceSoap();
        
        try{
            test58.Get_Fair(1234);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_FairList();
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_FairListByLangId(123);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_FairListByWebId(1111);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_FairListByWebIdLangId(111, 1223);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_fuar_userByID(145);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_News(456);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_NewsList();
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_NewsListByLangId(2563);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_NewsListByWebId(5555);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_NewsListByWebIdLangId(555, 111);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_Slider(789);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_SliderList();
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_SliderListByLangId(5693);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_SliderListByWebId(7777);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Get_SliderListByWebIdLangId(4324, 5454);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Getbilet_proByID(23213);
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.GenerateCode();
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.Getbilet_proByKOD('KOD', 'web_id');
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.GetCalendar('lang');
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.GetMailPatternByMailType('MailType');
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
        
        try{
            test58.GetMailSettingsUtilByMailTopic('MailTopic');
        }
        catch(Exception ex){
            //system.debug('ex: ' + ex);
        }
    }
}